# Site settings
title: ':(){ :|:&};:'
author: ludwhe
email: _@ludwhe.dev

description: >- # this means to ignore newlines until "baseurl:"
  Software engineer from France.
  My interests include Linux, free and open-source software,
  cloud computing, operating systems and web development.

# the subpath of your site
baseurl: ""
# the base hostname & protocol for your site
url: "https://pages.ludwhe.dev"

github_username: ludwhe
linkedin_username: louis-heili

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
