# Site settings
title: ludwhe's blog
email: _@ludwhe.dev
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science MEng. student from France.
  My interests include Linux, free and open-source software, cloud computing,
  operating systems and web development.
baseurl: "" # the subpath of your site
url: "https://blog.ludwhe.dev" # the base hostname & protocol for your site
# twitter_username: ""
github_username:  ludwhe

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
